; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^7.6.0
	bogde/HX711@^0.7.5
build_src_filter = 
	-<*>
	+<main_sensor.cpp>

[env:heltecremote]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_echo = yes
build_src_filter = 
	-<*>
	+<main_remote.cpp>
lib_ldf_mode = deep+
build_flags = 
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SPI/src
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SD/src
lib_deps = 
	jgromes/RadioLib@^7.6.0
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	bogde/HX711@^0.7.5

[env:heltecengine]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_echo = yes
build_src_filter = 
	-<*>
	+<main_engine.cpp>
lib_deps = 
	jgromes/RadioLib@^7.6.0
	bogde/HX711@^0.7.5

[env:picoengine]
platform = raspberrypi
board = rpipico2
monitor_speed = 115200
monitor_echo = yes
framework = arduino
build_src_filter = 
	-<*>
	+<main_engine.cpp>
lib_deps = 
	jgromes/RadioLib@^7.6.0
	bogde/HX711@^0.7.5
